# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "master" do |node|
      node.vm.network "private_network", ip: "192.168.65.10"
      node.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = "4"
      end
  end

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      ip = "192.168.65.1#{i}"
      node.vm.network "private_network", ip: ip
      node.vm.provider :virtualbox do |vb|
        vb.memory = 2048
        vb.cpus = "4"
      end
    end
  end
end
