# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
   v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end

  config.vm.define "master" do |node|
      node.vm.network "private_network", ip: "192.168.65.10"
      # node.vm.provision :shell, :inline => "sudo ip addr flush dev enp0s8"
      # node.vm.provision :shell, :inline => "sudo ip addr add 192.168.65.10/24 dev enp0s8"
      node.vm.provider :virtualbox do |vb|
        vb.memory = 4092
        vb.cpus = 4
      end
  end

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      ip = "192.168.65.1#{i}"
      node.vm.network "private_network", ip: ip
      # node.vm.provision :shell, :inline => "sudo ip addr flush dev enp0s8"
      # node.vm.provision :shell, :inline => "sudo ip addr add #{ip}/24 dev enp0s8"
      node.vm.provider :virtualbox do |vb|
        vb.memory = 3072
        vb.cpus = 4
      end
    end
  end
end
